/**
 * Migration file template
 * Generated by Normal CLI
 */

module.exports = {
  /**
   * Run the migration
   * @param {import('normaljs').Repository} repo - The Normal repository instance
   * @param {import('knex').Knex} knex - The Knex instance for raw queries
   */
  async up(repo, knex) {
    // Add migration logic here
    // Example: await repo.sync({ force: false });
  },

  /**
   * Rollback the migration
   * @param {import('normaljs').Repository} repo - The Normal repository instance
   * @param {import('knex').Knex} knex - The Knex instance for raw queries
   */
  async down(repo, knex) {
    // Add rollback logic here
    // Example: await knex.schema.dropTable('table_name');
  },
};
