/**
 * Model template
 * Generated by Normal CLI
 */

class {{modelName}} {
  static name = '{{modelName}}';
  static table = '{{tableName}}';
  static fields = {
    id: 'primary',
    {{#each attributes}}
    {{name}}: {{#if options}}{{{options}}}{{else}}'{{type}}'{{/if}},
    {{/each}}
    created_at: { type: 'datetime', default: () => new Date() },
    updated_at: { type: 'datetime', default: () => new Date() },
  };
}

module.exports = {{modelName}};
