/**
 * Seed file template
 * Generated by Normal CLI
 */

module.exports = {
  /**
   * Run the seed
   * @param {import('normaljs').Repository} repo - The Normal repository instance
   * @param {import('knex').Knex} knex - The Knex instance for raw queries
   */
  async up(repo, knex) {
    // Add seed data here
    // Example:
    // const Users = repo.get('Users');
    // await Users.create({ firstname: 'John', lastname: 'Doe', email: 'john@example.com' });
  },

  /**
   * Rollback the seed (optional)
   * @param {import('normaljs').Repository} repo - The Normal repository instance
   * @param {import('knex').Knex} knex - The Knex instance for raw queries
   */
  async down(repo, knex) {
    // Add logic to remove seed data
  },
};
